{
  programs.claude-code = {
    settings = {
      permissions = {
        allow = [
          "Bash(*--help*)"
          "Bash(*--version*)"
          "Bash(* ./tmp/**)"
          "Bash(awk *)"
          "Bash(basename *)"
          "Bash(bd *)"
          "Bash(cat *)"
          "Bash(claude config *)"
          "Bash(claude mcp list)"
          "Bash(column *)"
          "Bash(comm *)"
          "Bash(cut *)"
          "Bash(date *)"
          "Bash(diff *)"
          "Bash(dirname *)"
          "Bash(du *)"
          "Bash(echo *)"
          "Bash(file *)"
          "Bash(find *)"
          "Bash(gh pr checks *)"
          "Bash(gh pr diff *)"
          "Bash(gh pr list *)"
          "Bash(gh pr view *)"
          "Bash(gh release list *)"
          "Bash(gh release view *)"
          "Bash(gh repo view *)"
          "Bash(gh run list *)"
          "Bash(gh run view *)"
          "Bash(gh run watch *)"
          "Bash(gh search *)"
          "Bash(git -C *)"
          "Bash(git branch *)"
          "Bash(git check-ignore *)"
          "Bash(git diff *)"
          "Bash(git fetch *)"
          "Bash(git grep *)"
          "Bash(git log *)"
          "Bash(git ls-tree *)"
          "Bash(git rev-list *)"
          "Bash(git rev-parse *)"
          "Bash(git show *)"
          "Bash(git show-branch *)"
          "Bash(git shortlog *)"
          "Bash(git stash list *)"
          "Bash(git stash show *)"
          "Bash(git status*)"
          "Bash(git worktree add *)"
          "Bash(git worktree list *)"
          "Bash(go *)"
          "Bash(gofmt *)"
          "Bash(golang-ci lint *)"
          "Bash(grep *)"
          "Bash(helm get *)"
          "Bash(helm lint *)"
          "Bash(helm list *)"
          "Bash(helm show *)"
          "Bash(helm template *)"
          "Bash(head *)"
          "Bash(jq *)"
          "Bash(kubectl config current-context)"
          "Bash(kubectl config get-contexts *)"
          "Bash(kubectl describe *)"
          "Bash(kubectl events *)"
          "Bash(kubectl get *)"
          "Bash(kubectl logs *)"
          "Bash(kubectl top *)"
          "Bash(kubectl api-resources *)"
          "Bash(kubectl explain *)"
          "Bash(kubectl version *)"
          "Bash(logcli *)"
          "Bash(ls *)"
          "Bash(nl *)"
          "Bash(readlink *)"
          "Bash(stat *)"
          "Bash(uniq *)"
          "Bash(which *)"
          "Bash(make build)"
          "Bash(make test)"
          "Bash(mkdir *)"
          "Bash(nix develop *)"
          "Bash(nix eval *)"
          "Bash(nix flake show *)"
          "Bash(nix why-depends *)"
          "Bash(nix-instantiate --eval *)"
          "Bash(nix-instantiate --parse *)"
          "Bash(pbcopy *)"
          "Bash(pbpaste *)"
          "Bash(sed -n *)"
          "Bash(sort *)"
          "Bash(tail *)"
          "Bash(test *)"
          "Bash(tr *)"
          "Bash(wc *)"
          "Edit(./tmp/**)"
          "Edit(~/Documents/Notes/*.md)"
          "Glob"
          "Grep"
          "mcp__atlassian__atlassianUserInfo"
          "mcp__atlassian__fetch"
          "mcp__atlassian__fetchAtlassian"
          "mcp__atlassian__getAccessibleAtlassianResources"
          "mcp__atlassian__getConfluenceCommentChildren"
          "mcp__atlassian__getConfluencePage"
          "mcp__atlassian__getConfluencePageDescendants"
          "mcp__atlassian__getConfluencePageFooterComments"
          "mcp__atlassian__getConfluencePageInlineComments"
          "mcp__atlassian__getConfluenceSpaces"
          "mcp__atlassian__getContentFormatGuide"
          "mcp__atlassian__getIssueLinkTypes"
          "mcp__atlassian__getJiraIssue"
          "mcp__atlassian__getJiraIssueRemoteIssueLinks"
          "mcp__atlassian__getJiraIssueTypeMetaWithFields"
          "mcp__atlassian__getJiraProjectIssueTypesMetadata"
          "mcp__atlassian__getPagesInConfluenceSpace"
          "mcp__atlassian__getTransitionsForJiraIssue"
          "mcp__atlassian__getVisibleJiraProjects"
          "mcp__atlassian__lookupJiraAccountId"
          "mcp__atlassian__search"
          "mcp__atlassian__searchAtlassian"
          "mcp__atlassian__searchConfluenceUsingCql"
          "mcp__atlassian__searchJiraIssuesUsingJql"
          "mcp__jira__atlassianUserInfo"
          "mcp__jira__fetch"
          "mcp__jira__getAccessibleAtlassianResources"
          "mcp__jira__getConfluencePage"
          "mcp__jira__getConfluencePageDescendants"
          "mcp__jira__getConfluencePageFooterComments"
          "mcp__jira__getConfluencePageInlineComments"
          "mcp__jira__getConfluenceSpaces"
          "mcp__jira__getJiraIssue"
          "mcp__jira__getJiraIssueRemoteIssueLinks"
          "mcp__jira__getJiraIssueTypeMetaWithFields"
          "mcp__jira__getJiraProjectIssueTypesMetadata"
          "mcp__jira__getPagesInConfluenceSpace"
          "mcp__jira__getTransitionsForJiraIssue"
          "mcp__jira__getVisibleJiraProjects"
          "mcp__jira__lookupJiraAccountId"
          "mcp__jira__search"
          "mcp__jira__searchConfluenceUsingCql"
          "mcp__jira__searchJiraIssuesUsingJql"
          "mcp__glean_default__Brave_Actions_web_search"
          "mcp__glean_default__code_search"
          "mcp__glean_default__employee_search"
          "mcp__glean_default__memory"
          "mcp__glean_default__memory_schema"
          "mcp__glean_default__read_document"
          "mcp__glean_default__search"
          "mcp__glean_default__user_activity"
          "mcp__mom__ask_mom"
          "mcp__o11yops__describe_clickhouse_table"
          "mcp__o11yops__generate_deeplink"
          "mcp__o11yops__get_dashboard_by_uid"
          "mcp__o11yops__get_dashboard_panel_queries"
          "mcp__o11yops__get_dashboard_property"
          "mcp__o11yops__get_dashboard_summary"
          "mcp__o11yops__get_datasource"
          "mcp__o11yops__get_metrics_for_symptoms"
          "mcp__o11yops__get_netbox_model_metadata"
          "mcp__o11yops__get_policy_for_symptoms"
          "mcp__o11yops__list_clickhouse_tables"
          "mcp__o11yops__list_customer_datasources"
          "mcp__o11yops__list_datasources"
          "mcp__o11yops__list_logs_label_names"
          "mcp__o11yops__list_logs_label_values"
          "mcp__o11yops__list_metric_label_names"
          "mcp__o11yops__list_metric_label_values"
          "mcp__o11yops__list_metric_metadata"
          "mcp__o11yops__list_metric_names"
          "mcp__o11yops__list_netbox_models"
          "mcp__o11yops__list_netbox_sites"
          "mcp__o11yops__lookup_customer_org_id"
          "mcp__o11yops__query_clickhouse"
          "mcp__o11yops__query_filesystem_coreweave_docs"
          "mcp__o11yops__query_logs"
          "mcp__o11yops__query_logs_patterns"
          "mcp__o11yops__query_logs_stats"
          "mcp__o11yops__query_metric_histogram"
          "mcp__o11yops__query_metrics"
          "mcp__o11yops__query_netbox_resources"
          "mcp__o11yops__query_observability_knowledge_base"
          "mcp__o11yops__search_coreweave_docs"
          "mcp__o11yops__search_dashboards"
          "mcp__o11yops__search_folders"
          "mcp__o11yops__search_logs"
          # mission-control-mcp exposes the same read-only tools as o11yops under a plugin prefix
          "mcp__plugin_hm_mission-control-mcp__describe_clickhouse_table"
          "mcp__plugin_hm_mission-control-mcp__generate_deeplink"
          "mcp__plugin_hm_mission-control-mcp__get_dashboard_by_uid"
          "mcp__plugin_hm_mission-control-mcp__get_dashboard_panel_queries"
          "mcp__plugin_hm_mission-control-mcp__get_dashboard_property"
          "mcp__plugin_hm_mission-control-mcp__get_dashboard_summary"
          "mcp__plugin_hm_mission-control-mcp__get_datasource"
          "mcp__plugin_hm_mission-control-mcp__get_metrics_for_symptoms"
          "mcp__plugin_hm_mission-control-mcp__get_netbox_model_metadata"
          "mcp__plugin_hm_mission-control-mcp__get_policy_for_symptoms"
          "mcp__plugin_hm_mission-control-mcp__list_clickhouse_tables"
          "mcp__plugin_hm_mission-control-mcp__list_customer_datasources"
          "mcp__plugin_hm_mission-control-mcp__list_datasources"
          "mcp__plugin_hm_mission-control-mcp__list_logs_label_names"
          "mcp__plugin_hm_mission-control-mcp__list_logs_label_values"
          "mcp__plugin_hm_mission-control-mcp__list_metric_label_names"
          "mcp__plugin_hm_mission-control-mcp__list_metric_label_values"
          "mcp__plugin_hm_mission-control-mcp__list_metric_metadata"
          "mcp__plugin_hm_mission-control-mcp__list_metric_names"
          "mcp__plugin_hm_mission-control-mcp__list_netbox_models"
          "mcp__plugin_hm_mission-control-mcp__list_netbox_sites"
          "mcp__plugin_hm_mission-control-mcp__lookup_customer_org_id"
          "mcp__plugin_hm_mission-control-mcp__query_clickhouse"
          "mcp__plugin_hm_mission-control-mcp__query_filesystem_coreweave_docs"
          "mcp__plugin_hm_mission-control-mcp__query_logs"
          "mcp__plugin_hm_mission-control-mcp__query_logs_patterns"
          "mcp__plugin_hm_mission-control-mcp__query_logs_stats"
          "mcp__plugin_hm_mission-control-mcp__query_metric_histogram"
          "mcp__plugin_hm_mission-control-mcp__query_metrics"
          "mcp__plugin_hm_mission-control-mcp__query_netbox_resources"
          "mcp__plugin_hm_mission-control-mcp__query_observability_knowledge_base"
          "mcp__plugin_hm_mission-control-mcp__search_coreweave_docs"
          "mcp__plugin_hm_mission-control-mcp__search_dashboards"
          "mcp__plugin_hm_mission-control-mcp__search_folders"
          "mcp__plugin_hm_mission-control-mcp__search_logs"
          "mcp__stargate-pagerduty__browse_activity"
          "mcp__stargate-pagerduty__browse_alert_grouping"
          "mcp__stargate-pagerduty__browse_change_events"
          "mcp__stargate-pagerduty__browse_escalation_policies"
          "mcp__stargate-pagerduty__browse_event_orchestrations"
          "mcp__stargate-pagerduty__browse_incidents"
          "mcp__stargate-pagerduty__browse_schedules"
          "mcp__stargate-pagerduty__browse_services"
          "mcp__stargate-pagerduty__browse_status_pages"
          "mcp__stargate-pagerduty__browse_teams"
          "mcp__stargate-pagerduty__browse_users"
          "Read"
          "Read(./tmp/**)"
          "WebFetch"
          "WebSearch"
        ];
        ask = [
          "Bash(git add *)"
          "Bash(git commit *)"
          "Bash(git push *)"
          "Bash(kubectl annotate *)"
          "Bash(kubectl delete *)"
          "Bash(kubectl edit *)"
          "Bash(kubectl exec *)"
        ];
        deny = [
          "Read(.aws/credentials)"
          "Read(.kube/**)"
          "Read(.ssh/**)"
        ];
      };
    };
  };
}
