{
  programs.claude-code = {
    settings = {
      alwaysThinkingEnabled = false;
      permissions = {
        allow = [
          "Bash(*--help*)"
          "Bash(*--version*)"
          "Bash(* ./tmp/**)"
          "Bash(awk *)"
          "Bash(bd *)"
          "Bash(cat *)"
          "Bash(claude config *)"
          "Bash(claude mcp list)"
          "Bash(date *)"
          "Bash(echo *)"
          "Bash(find *)"
          "Bash(gh pr checks *)"
          "Bash(gh pr diff *)"
          "Bash(gh pr list *)"
          "Bash(gh pr view *)"
          "Bash(gh release list *)"
          "Bash(gh release view *)"
          "Bash(gh run list *)"
          "Bash(gh run view *)"
          "Bash(gh run watch *)"
          "Bash(gh search *)"
          "Bash(git -C *)"
          "Bash(git branch *)"
          "Bash(git check-ignore *)"
          "Bash(git diff *)"
          "Bash(git fetch *)"
          "Bash(git grep *)"
          "Bash(git log *)"
          "Bash(git ls-tree *)"
          "Bash(git rev-list *)"
          "Bash(git rev-parse *)"
          "Bash(git show *)"
          "Bash(git stash list *)"
          "Bash(git stash show *)"
          "Bash(git status*)"
          "Bash(git worktree list *)"
          "Bash(grep *)"
          "Bash(head *)"
          "Bash(jq *)"
          "Bash(kubectl get *)"
          "Bash(ls *)"
          "Bash(mkdir *)"
          "Bash(nix eval *)"
          "Bash(nix flake show *)"
          "Bash(nix why-depends *)"
          "Bash(sort *)"
          "Bash(tail *)"
          "Bash(test *)"
          "Bash(tr *)"
          "Bash(wc *)"
          "Edit(./tmp/**)"
          "Glob"
          "Grep"
          "mcp__atlassian__atlassianUserInfo"
          "mcp__atlassian__fetchAtlassian"
          "mcp__atlassian__getAccessibleAtlassianResources"
          "mcp__atlassian__getIssueLinkTypes"
          "mcp__atlassian__searchAtlassian"
          "mcp__atlassian__searchJiraIssuesUsingJql"
          "mcp__jira__atlassianUserInfo"
          "mcp__jira__fetch"
          "mcp__jira__getAccessibleAtlassianResources"
          "mcp__jira__getConfluencePage"
          "mcp__jira__getConfluencePageDescendants"
          "mcp__jira__getConfluencePageFooterComments"
          "mcp__jira__getConfluencePageInlineComments"
          "mcp__jira__getConfluenceSpaces"
          "mcp__jira__getJiraIssue"
          "mcp__jira__getJiraIssueRemoteIssueLinks"
          "mcp__jira__getJiraIssueTypeMetaWithFields"
          "mcp__jira__getJiraProjectIssueTypesMetadata"
          "mcp__jira__getPagesInConfluenceSpace"
          "mcp__jira__getTransitionsForJiraIssue"
          "mcp__jira__getVisibleJiraProjects"
          "mcp__jira__lookupJiraAccountId"
          "mcp__jira__search"
          "mcp__jira__searchConfluenceUsingCql"
          "mcp__jira__searchJiraIssuesUsingJql"
          "Read"
          "Read(./tmp/**)"
          "WebFetch"
          "WebSearch"
          "Write(./tmp/**)"
          "Write(~/Documents/Notes/*.md)"
        ];
        ask = [
          "Bash(git add *)"
          "Bash(git commit *)"
          "Bash(git push *)"
        ];
        deny = [
          "Read(.kube/**)"
          "Read(.ssh/**)"
        ];
      };
    };
  };
}
